# Docker image used for building scsi2sd-util6 for Windows and Linux.

# Ensure git is using lf line endings on windows. Anything else breaks the autoconf scripts:
# git config --global core.eol lf
# git config --global core.autocrlf input

# docker build -f Dockerfile-linux -t scsi2sd-util-build .
#
# One-off prep: (this could be added to the makefile !)
# docker run --rm -v ${PWD}:/src/scsi2sd-util6 -w /src/scsi2sd-util6/libusb-1.0.23 scsi2sd-util-build autoreconf -i
# docker run --rm -v ${PWD}:/src/scsi2sd-util6 -w /src/scsi2sd-util6/dfu-util scsi2sd-util-build sh -c ./autogen.sh
#
# Run make via "sh" to ensure $PWD is set correctly:
# docker run --rm -v ${PWD}/../../:/app -w /app/src/scsi2sd-util6/ scsi2sd-util-build sh -c "make -j"
# docker run --rm -v ${PWD}/../../:/app -w /app/src/scsi2sd-util6/ scsi2sd-util-build sh -c "make -j TARGET=Win32"
# docker run --rm -v ${PWD}/../../:/app -w /app/src/scsi2sd-util6/ scsi2sd-util-build sh -c "make -j TARGET=Win64"
FROM debian:bullseye-slim

RUN apt update && apt install -y g++ g++-mingw-w64 make automake libtool pkg-config
RUN apt update && apt install -y libudev-dev libgtk2.0-dev libusb-1.0-0-dev