M48
; DRILL file {KiCad 6.0.5-a6ca702e91~116~ubuntu21.10.1} date Thu 26 Jan 2023 05:59:24 AM MST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-26T05:59:24-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.5-a6ca702e91~116~ubuntu21.10.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.888Y-4.26
T0
M30
