M48
; DRILL file {KiCad 8.0.2} date 2024-11-27T18:37:01-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-27T18:37:01-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X1.5059Y0.228
X1.5059Y0.0004
T2
X1.2146Y0.9329
X1.2224Y-0.9234
X1.7461Y1.2026
M30
