/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <SCSI_In_DBx_aliases.h>
#include <SCSI_In_DBx.h>
#include <SCSI_Out_DBx_aliases.h>
#include <SCSI_Out_DBx.h>
#include <SDCard.h>
#include <SDCard_PVT.h>
#include <SD_MISO_aliases.h>
#include <SD_MISO.h>
#include <SD_MOSI_aliases.h>
#include <SD_MOSI.h>
#include <SD_SCK_aliases.h>
#include <SD_SCK.h>
#include <SD_CS_aliases.h>
#include <SD_CS.h>
#include <SD_DAT1_aliases.h>
#include <SD_DAT1.h>
#include <SD_DAT2_aliases.h>
#include <SD_DAT2.h>
#include <SD_WP_aliases.h>
#include <SD_WP.h>
#include <SD_CD_aliases.h>
#include <SD_CD.h>
#include <SCSI_ID_aliases.h>
#include <PARITY_EN_aliases.h>
#include <PARITY_EN.h>
#include <SCSI_In_aliases.h>
#include <SCSI_Out_aliases.h>
#include <LED1_aliases.h>
#include <LED1.h>
#include <SD_Init_Clk.h>
#include <SD_Data_Clk.h>
#include <SD_Clk_Ctl.h>
#include <SCSI_RST_aliases.h>
#include <SCSI_RST.h>
#include <SCSI_ATN_aliases.h>
#include <SCSI_ATN.h>
#include <SCSI_RST_ISR.h>
#include <SCSI_ATN_ISR.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

