#!/usr/bin/env python3
# Copyright (C) 2026 Eric Helgeson
#
# This file is part of BlueSCSI
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""
Analyze GCC -fstack-usage (.su) files to find functions with large stack frames.

Parses .su files generated by -fstack-usage and reports functions that exceed
a configurable threshold. Intended to catch stack-heavy functions early, before
they cause overflows on the RP2040 (2KB) or RP2350 (3KB) targets.

Usage:
    python3 utils/check_stack_usage.py <build_dir> [--warn <bytes>] [--fail <bytes>] [--top N]

Examples:
    python3 utils/check_stack_usage.py build/
    python3 utils/check_stack_usage.py build/Ultra --warn 256 --fail 768
    python3 utils/check_stack_usage.py build/ --top 20
"""

import argparse
import os
import sys
from pathlib import Path


def parse_su_file(path):
    """Parse a .su file and yield (source_location, function_name, frame_size, qualifier) tuples."""
    try:
        with open(path, 'r') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                # Format: source:line:col:function_name\tframe_size\tqualifier
                parts = line.split('\t')
                if len(parts) < 2:
                    continue
                location_and_func = parts[0]
                frame_size = int(parts[1])
                qualifier = parts[2] if len(parts) > 2 else 'static'

                # Split location:line:col:function from the first field
                # Find the function name after the last colon-number-colon pattern
                # Format is: /path/to/file.cpp:line:col:function_name
                try:
                    # Split on tab already done; first part has location:func
                    # We need to extract function name from source:line:col:name
                    # Find positions of colons
                    colon_positions = [i for i, c in enumerate(location_and_func) if c == ':']
                    if len(colon_positions) >= 3:
                        func_start = colon_positions[2] + 1
                        func_name = location_and_func[func_start:]
                        source_loc = location_and_func[:colon_positions[2]]
                    else:
                        func_name = location_and_func
                        source_loc = ''
                except (IndexError, ValueError):
                    func_name = location_and_func
                    source_loc = ''

                yield source_loc, func_name, frame_size, qualifier
    except (IOError, UnicodeDecodeError):
        pass


def shorten_path(path):
    """Shorten absolute paths to be relative to common prefixes."""
    path = str(path)
    # Try to make relative to project root
    markers = ['/src/', '/lib/', '/build/']
    for marker in markers:
        idx = path.find(marker)
        if idx >= 0:
            return path[idx + 1:]
    # Fall back to basename
    return os.path.basename(path)


def main():
    parser = argparse.ArgumentParser(description='Analyze stack usage from GCC .su files')
    parser.add_argument('build_dir', nargs='?', default='build/',
                        help='Build directory to scan for .su files (default: build/)')
    parser.add_argument('--warn', type=int, default=384,
                        help='Warn threshold in bytes (default: 384)')
    parser.add_argument('--fail', type=int, default=1024,
                        help='Fail threshold in bytes (default: 1024)')
    parser.add_argument('--top', type=int, default=10,
                        help='Show top N functions (default: 10)')
    parser.add_argument('--all', action='store_true',
                        help='Show all functions above warn threshold')
    parser.add_argument('--dynamic', action='store_true',
                        help='Also flag functions with dynamic (VLA) stack usage')
    args = parser.parse_args()

    build_dir = Path(args.build_dir)
    if not build_dir.exists():
        print(f"Error: {build_dir} does not exist", file=sys.stderr)
        sys.exit(1)

    # Collect all .su files
    su_files = list(build_dir.rglob('*.su'))
    if not su_files:
        print(f"No .su files found in {build_dir}")
        print("Build with -fstack-usage to generate them:")
        print("  cmake -DCMAKE_C_FLAGS_RELEASE=-fstack-usage -DCMAKE_CXX_FLAGS_RELEASE=-fstack-usage ..")
        sys.exit(0)

    # Parse all entries, deduplicate by function name (keep largest)
    entries = {}  # func_name -> (source_loc, frame_size, qualifier)
    dynamic_entries = []

    for su_file in su_files:
        for source_loc, func_name, frame_size, qualifier in parse_su_file(su_file):
            if qualifier == 'dynamic' and args.dynamic:
                dynamic_entries.append((source_loc, func_name, frame_size, qualifier))

            key = func_name
            if key not in entries or frame_size > entries[key][1]:
                entries[key] = (source_loc, frame_size, qualifier)

    if not entries:
        print(f"No stack usage data found in {len(su_files)} .su files")
        sys.exit(0)

    # Sort by frame size descending
    sorted_entries = sorted(entries.items(), key=lambda x: x[1][1], reverse=True)

    # Determine targets scanned
    targets = set()
    for su_file in su_files:
        parts = su_file.parts
        for i, p in enumerate(parts):
            if p == 'CMakeFiles':
                if i > 0:
                    targets.add(parts[i - 1])
                break

    # Print header
    print(f"Stack Usage Analysis ({len(entries)} functions from {len(su_files)} .su files)")
    if targets:
        print(f"Targets: {', '.join(sorted(targets))}")
    print(f"Thresholds: warn >= {args.warn} B, fail >= {args.fail} B")
    print()

    # Print top N
    fail_count = 0
    warn_count = 0

    if args.all:
        display = [(name, data) for name, data in sorted_entries if data[1] >= args.warn]
    else:
        display = sorted_entries[:args.top]

    if display:
        # Column widths
        max_size = max(d[1] for _, d in display)
        size_width = len(str(max_size))

        print(f"{'Bytes':>{size_width + 1}}  {'Function'}")
        print(f"{'─' * (size_width + 1)}  {'─' * 60}")

        for func_name, (source_loc, frame_size, qualifier) in display:
            short_loc = shorten_path(source_loc)

            # Status indicator
            if frame_size >= args.fail:
                marker = '!!'
                fail_count += 1
            elif frame_size >= args.warn:
                marker = ' >'
                warn_count += 1
            else:
                marker = '  '

            dyn = ' [dynamic]' if qualifier == 'dynamic' else ''
            print(f"{marker}{frame_size:>{size_width}}  {func_name}{dyn}")
            if source_loc:
                print(f"{'':>{size_width + 3}}  {short_loc}")

    # Count totals (including non-displayed)
    for _, (_, frame_size, _) in sorted_entries:
        if frame_size >= args.fail:
            if not args.all:
                fail_count += 1
        elif frame_size >= args.warn:
            if not args.all:
                warn_count += 1

    # Deduplicate counting - we counted display items twice if not --all
    if not args.all:
        fail_count = sum(1 for _, (_, sz, _) in sorted_entries if sz >= args.fail)
        warn_count = sum(1 for _, (_, sz, _) in sorted_entries if args.warn <= sz < args.fail)

    print()
    print(f"Summary: {fail_count} over fail threshold, {warn_count} warnings, {len(entries)} total functions")

    if dynamic_entries:
        print(f"\n{len(dynamic_entries)} functions with dynamic (VLA) stack usage detected")

    if fail_count > 0:
        print(f"\nERROR: {fail_count} function(s) exceed {args.fail}-byte stack frame limit")
        sys.exit(1)

    sys.exit(0)


if __name__ == '__main__':
    main()
