# Assume newlib gcc toolchain
ARMCC=arm-none-eabi-gcc
OBJCOPY=arm-none-eabi-objcopy

#CPPFLAGS=-DSTM32F446xx -DSTM32F4xx -DUSE_HAL_DRIVER -Wall -DS2S_USB_HS
CPPFLAGS=-DSTM32F446xx -DSTM32F4xx -DUSE_HAL_DRIVER -Wall -DS2S_USB_FS
CFLAGS=-mcpu=cortex-m4 -mthumb -mslow-flash-data \
	-std=gnu11 \
	-specs=nosys.specs \
	-Os -g \

LDFLAGS= \
	"-Tsrc/firmware/link.ld" \

INCLUDE = -Iinclude


STM32CubeMX_INCUDE = \
	-ISTM32CubeMX/2021/Inc \
	-ISTM32CubeMX/2021/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc \
	-ISTM32CubeMX/2021/Middlewares/ST/STM32_USB_Host_Library/Core/Inc \
	-ISTM32CubeMX/2021/Drivers/CMSIS/Include \
	-ISTM32CubeMX/2021/Drivers/CMSIS/Device/ST/STM32F4xx/Include \
	-ISTM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Inc \
	-ISTM32CubeMX/2021/Middlewares/Third_Party/FatFs/src/ \
	-ISTM32CubeMX/2021/Middlewares/Third_Party/FatFs/src/drivers \
	-ISTM32CubeMX/2021/Middlewares/ST/STM32_USB_Device_Library/Core/Inc \
	-Isrc/firmware/usb_device \

all: build/firmware.V6.2021.dfu

build/2021/stm32cubemx/dma.o: STM32CubeMX/2021/Src/dma.c
build/2021/stm32cubemx/fmc.o: STM32CubeMX/2021/Src/fmc.c
build/2021/stm32cubemx/gpio.o: STM32CubeMX/2021/Src/gpio.c
build/2021/stm32cubemx/main.o: STM32CubeMX/2021/Src/main.c
build/2021/stm32cubemx/sdio.o: STM32CubeMX/2021/Src/sdio.c
build/2021/stm32cubemx/spi.o: STM32CubeMX/2021/Src/spi.c
build/2021/stm32cubemx/stm32f4xx_hal_msp.o: STM32CubeMX/2021/Src/stm32f4xx_hal_msp.c
build/2021/stm32cubemx/stm32f4xx_it.o: STM32CubeMX/2021/Src/stm32f4xx_it.c
build/2021/stm32cubemx/usart.o: STM32CubeMX/2021/Src/usart.c
build/2021/stm32cubemx/usbd_conf.o: STM32CubeMX/2021/Src/usbd_conf.c
build/2021/stm32cubemx/stm32f4xx_hal.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
build/2021/stm32cubemx/stm32f4xx_hal_cortex.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
build/2021/stm32cubemx/stm32f4xx_hal_dma.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c
build/2021/stm32cubemx/stm32f4xx_hal_flash.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c
build/2021/stm32cubemx/stm32f4xx_hal_flash_ex.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c
build/2021/stm32cubemx/stm32f4xx_hal_gpio.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c
build/2021/stm32cubemx/stm32f4xx_hal_hcd.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c
build/2021/stm32cubemx/stm32f4xx_hal_pcd.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c
build/2021/stm32cubemx/stm32f4xx_hal_pcd_ex.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c
build/2021/stm32cubemx/stm32f4xx_hal_pwr_ex.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c
build/2021/stm32cubemx/stm32f4xx_hal_rcc.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
build/2021/stm32cubemx/stm32f4xx_hal_rcc_ex.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c
build/2021/stm32cubemx/stm32f4xx_hal_sd.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c
build/2021/stm32cubemx/stm32f4xx_hal_spi.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c
build/2021/stm32cubemx/stm32f4xx_hal_sram.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c
build/2021/stm32cubemx/stm32f4xx_hal_tim.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c
build/2021/stm32cubemx/stm32f4xx_hal_tim_ex.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c
build/2021/stm32cubemx/stm32f4xx_hal_uart.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c
build/2021/stm32cubemx/stm32f4xx_ll_fmc.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmc.c
build/2021/stm32cubemx/stm32f4xx_ll_fsmc.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c
build/2021/stm32cubemx/stm32f4xx_ll_sdmmc.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c
build/2021/stm32cubemx/stm32f4xx_ll_usb.o: STM32CubeMX/2021/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c
build/2021/stm32cubemx/usbd_core.o: STM32CubeMX/2021/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
build/2021/stm32cubemx/usbd_ctlreq.o: STM32CubeMX/2021/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c
build/2021/stm32cubemx/usbd_ioreq.o: STM32CubeMX/2021/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c
build/2021/stm32cubemx/system_stm32f4xx.o: STM32CubeMX/2021/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c
build/2021/stm32cubemx/startup_stm32f446xx.o: STM32CubeMX/2021/Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/startup_stm32f446xx.s

STM32OBJS = \
	build/2021/stm32cubemx/dma.o \
	build/2021/stm32cubemx/fmc.o \
	build/2021/stm32cubemx/gpio.o \
	build/2021/stm32cubemx/main.o \
	build/2021/stm32cubemx/sdio.o \
	build/2021/stm32cubemx/spi.o \
	build/2021/stm32cubemx/stm32f4xx_hal_msp.o \
	build/2021/stm32cubemx/stm32f4xx_it.o \
	build/2021/stm32cubemx/usart.o \
	build/2021/stm32cubemx/usbd_conf.o \
	build/2021/stm32cubemx/stm32f4xx_hal.o \
	build/2021/stm32cubemx/stm32f4xx_hal_cortex.o \
	build/2021/stm32cubemx/stm32f4xx_hal_dma.o \
	build/2021/stm32cubemx/stm32f4xx_hal_flash.o \
	build/2021/stm32cubemx/stm32f4xx_hal_flash_ex.o \
	build/2021/stm32cubemx/stm32f4xx_hal_gpio.o \
	build/2021/stm32cubemx/stm32f4xx_hal_hcd.o \
	build/2021/stm32cubemx/stm32f4xx_hal_pcd.o \
	build/2021/stm32cubemx/stm32f4xx_hal_pcd_ex.o \
	build/2021/stm32cubemx/stm32f4xx_hal_pwr_ex.o \
	build/2021/stm32cubemx/stm32f4xx_hal_rcc.o \
	build/2021/stm32cubemx/stm32f4xx_hal_rcc_ex.o \
	build/2021/stm32cubemx/stm32f4xx_hal_sd.o \
	build/2021/stm32cubemx/stm32f4xx_hal_spi.o \
	build/2021/stm32cubemx/stm32f4xx_hal_sram.o \
	build/2021/stm32cubemx/stm32f4xx_hal_tim.o \
	build/2021/stm32cubemx/stm32f4xx_hal_tim_ex.o \
	build/2021/stm32cubemx/stm32f4xx_hal_uart.o \
	build/2021/stm32cubemx/stm32f4xx_ll_fmc.o \
	build/2021/stm32cubemx/stm32f4xx_ll_fsmc.o \
	build/2021/stm32cubemx/stm32f4xx_ll_sdmmc.o \
	build/2021/stm32cubemx/stm32f4xx_ll_usb.o \
	build/2021/stm32cubemx/usbd_core.o \
	build/2021/stm32cubemx/usbd_ctlreq.o \
	build/2021/stm32cubemx/usbd_ioreq.o \
	build/2021/stm32cubemx/system_stm32f4xx.o \
	build/2021/stm32cubemx/startup_stm32f446xx.o \

# Modified versin from stm32cubemx for a composite class with both
# mass-storage and HID interfaces
USBCOMPOSITE_SRC= \
	src/firmware/usb_device/usb_device.c \
	src/firmware/usb_device/usbd_composite.c \
	src/firmware/usb_device/usbd_desc.c \
	src/firmware/usb_device/usbd_hid.c \
	src/firmware/usb_device/usbd_msc_bot.c \
	src/firmware/usb_device/usbd_msc.c \
	src/firmware/usb_device/usbd_msc_data.c \
	src/firmware/usb_device/usbd_msc_scsi.c \
	src/firmware/usb_device/usbd_msc_storage_sd.c \

SRC = \
	src/firmware/bootloader.c \
	src/firmware/bsp.c \
	src/firmware/cdrom.c \
	src/firmware/config.c \
	src/firmware/disk.c \
	src/firmware/diagnostic.c \
	src/firmware/fpga.c \
	src/firmware/geometry.c \
	src/firmware/hidpacket.c \
	src/firmware/hwversion.c \
	src/firmware/inquiry.c \
	src/firmware/led.c \
	src/firmware/main.c \
	src/firmware/mo.c \
	src/firmware/mode.c \
	src/firmware/scsiPhy.c \
	src/firmware/scsi.c \
	src/firmware/sd.c \
	src/firmware/spinlock.c \
	src/firmware/tape.c \
	src/firmware/time.c \
	src/firmware/vendor.c \
	src/firmware/bsp_driver_sd.c \
	${USBCOMPOSITE_SRC}

build/2021/firmware.elf: $(SRC) rtl/fpga_bitmap.o $(STM32OBJS)
	$(ARMCC) $(CPPFLAGS) $(CFLAGS) -o $@ $(STM32CubeMX_INCUDE) $(INCLUDE) $^ $(LDFLAGS)
	@EBSS=`arm-none-eabi-nm build/2021/firmware.elf | grep _ebss | cut -f1 "-d "`; \
	echo HEAPSIZE = $$((0x2001C000 - 0x$${EBSS})) bytes
	@echo STACKSIZE = 16384 bytes


build/2021/firmware.bin: build/2021/firmware.elf
	$(OBJCOPY) -O binary $< $@

# Example to hard-code config within firmware
#sudo arm-none-eabi-objcopy --update-section .fixed_config=config.dat firmware.elf -O binary firmware.bin

build/2021/stm32cubemx/%.o:
	mkdir -p build/2021/stm32cubemx
	$(ARMCC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $(STM32CubeMX_INCUDE) $(INCLUDE) $^


build/2021/stm32cubemx/stm32f4xx_it.o:
	mkdir -p build/2021/stm32cubemx
	$(ARMCC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $(STM32CubeMX_INCUDE) $(INCLUDE) $^
	$(OBJCOPY) -N EXTI4_IRQHandler $@

build/2021/stm32cubemx/system_stm32f4xx.o:
	mkdir -p build/2021/stm32cubemx
	$(ARMCC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $(STM32CubeMX_INCUDE) $(INCLUDE) $^
	$(OBJCOPY) --redefine-sym SystemInit=OrigSystemInit $@

build/2021/scsiPhy.s: src/firmware/scsiPhy.c
	$(ARMCC) $(CPPFLAGS) $(CFLAGS) -S -o $@ $(STM32CubeMX_INCUDE) $(INCLUDE) $^


build/firmware.V6.2021.dfu: build/2021/firmware.bin
	python tools/dfu-convert.py -b 0x08000000:$< $@

clean:
	rm -f build/firmware.V6.2021.dfu
	rm -rf build/2021/

program:
	dfu-util --download build/firmware.V6.2021.dfu --alt 0

