// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// cmd_rsp //
// ------- //

#define cmd_rsp_wrap_target 0
#define cmd_rsp_wrap 9

static const uint16_t cmd_rsp_program_instructions[] = {
            //     .wrap_target
    0x6d01, //  0: out    pins, 1         side 3 [1] 
    0x1d40, //  1: jmp    x--, 0          side 7 [1] 
    0x0d60, //  2: jmp    !y, 0           side 3 [1] 
    0xf780, //  3: set    pindirs, 0      side 5 [3] 
    0xe780, //  4: set    pindirs, 0      side 1 [3] 
    0xb542, //  5: nop                    side 5 [1] 
    0x14c4, //  6: jmp    pin, 4          side 5     
    0x5401, //  7: in     pins, 1         side 5     
    0x8660, //  8: push   iffull block    side 1 [2] 
    0x1587, //  9: jmp    y--, 7          side 5 [1] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program cmd_rsp_program = {
    .instructions = cmd_rsp_program_instructions,
    .length = 10,
    .origin = -1,
};

static inline pio_sm_config cmd_rsp_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + cmd_rsp_wrap_target, offset + cmd_rsp_wrap);
    sm_config_set_sideset(&c, 3, false, false);
    return c;
}

static inline pio_sm_config pio_cmd_rsp_program_config(uint offset, uint cmd_pin, uint clk_pin, uint16_t div_int, uint8_t div_frac) {
    pio_sm_config c = cmd_rsp_program_get_default_config(offset);
    sm_config_set_sideset_pins(&c, clk_pin - 2);
    sm_config_set_out_pins(&c, cmd_pin, 5);
    sm_config_set_in_pins(&c, cmd_pin);
    sm_config_set_set_pins(&c, cmd_pin, 5);
    sm_config_set_jmp_pin(&c, cmd_pin);
    sm_config_set_in_shift(&c, false, false, 8);
    sm_config_set_out_shift(&c, false, true, 8);
    sm_config_set_clkdiv_int_frac(&c, div_int, div_frac);
    return c;
}

#endif

// ----------------------- //
// rd_data_w_clock_default //
// ----------------------- //

#define rd_data_w_clock_default_wrap_target 0
#define rd_data_w_clock_default_wrap 7

static const uint16_t rd_data_w_clock_default_program_instructions[] = {
            //     .wrap_target
    0xa822, //  0: mov    x, y            side 2     
    0xab42, //  1: nop                    side 2 [3] 
    0x1bc1, //  2: jmp    pin, 1          side 6 [3] 
    0xaa42, //  3: nop                    side 2 [2] 
    0xb942, //  4: nop                    side 6 [1] 
    0x4a04, //  5: in     pins, 4         side 2 [2] 
    0x9860, //  6: push   iffull block    side 6     
    0x1845, //  7: jmp    x--, 5          side 6     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rd_data_w_clock_default_program = {
    .instructions = rd_data_w_clock_default_program_instructions,
    .length = 8,
    .origin = -1,
};

static inline pio_sm_config rd_data_w_clock_default_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rd_data_w_clock_default_wrap_target, offset + rd_data_w_clock_default_wrap);
    sm_config_set_sideset(&c, 3, false, false);
    return c;
}

static inline pio_sm_config pio_rd_data_w_clock_default_program_config(uint offset, uint d0_pin, uint clk_pin, float clk_div) {
  pio_sm_config c = rd_data_w_clock_default_program_get_default_config(offset);
  sm_config_set_sideset_pins(&c, clk_pin - 2);
  sm_config_set_in_pins(&c, d0_pin);
  sm_config_set_jmp_pin(&c, d0_pin);
  sm_config_set_in_shift(&c, false, false, 32);
  sm_config_set_out_shift(&c, false, true, 32);
  sm_config_set_clkdiv(&c, clk_div);
  return c;
}

#endif

// -------------------------- //
// rd_data_w_clock_high_speed //
// -------------------------- //

#define rd_data_w_clock_high_speed_wrap_target 0
#define rd_data_w_clock_high_speed_wrap 5

static const uint16_t rd_data_w_clock_high_speed_program_instructions[] = {
            //     .wrap_target
    0xa822, //  0: mov    x, y            side 2     
    0xaa42, //  1: nop                    side 2 [2] 
    0x1ac1, //  2: jmp    pin, 1          side 6 [2] 
    0xaa42, //  3: nop                    side 2 [2] 
    0x5904, //  4: in     pins, 4         side 6 [1] 
    0x0a44, //  5: jmp    x--, 4          side 2 [2] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rd_data_w_clock_high_speed_program = {
    .instructions = rd_data_w_clock_high_speed_program_instructions,
    .length = 6,
    .origin = -1,
};

static inline pio_sm_config rd_data_w_clock_high_speed_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rd_data_w_clock_high_speed_wrap_target, offset + rd_data_w_clock_high_speed_wrap);
    sm_config_set_sideset(&c, 3, false, false);
    return c;
}

static inline pio_sm_config pio_rd_data_w_clock_high_speed_program_config(uint offset, uint d0_pin, uint clk_pin, float clk_div) {
  pio_sm_config c = rd_data_w_clock_high_speed_program_get_default_config(offset);
  sm_config_set_sideset_pins(&c, clk_pin - 2);
  sm_config_set_in_pins(&c, d0_pin);
  sm_config_set_jmp_pin(&c, d0_pin);
  sm_config_set_in_shift(&c, false, true, 32);
  sm_config_set_out_shift(&c, false, true, 32);
  sm_config_set_clkdiv(&c, clk_div);
  return c;
}

#endif

// -------------------------------- //
// rd_data_w_clock_ultra_high_speed //
// -------------------------------- //

#define rd_data_w_clock_ultra_high_speed_wrap_target 0
#define rd_data_w_clock_ultra_high_speed_wrap 5

static const uint16_t rd_data_w_clock_ultra_high_speed_program_instructions[] = {
            //     .wrap_target
    0xa822, //  0: mov    x, y            side 2     
    0xa942, //  1: nop                    side 2 [1] 
    0x19c1, //  2: jmp    pin, 1          side 6 [1] 
    0xa942, //  3: nop                    side 2 [1] 
    0x5804, //  4: in     pins, 4         side 6     
    0x0944, //  5: jmp    x--, 4          side 2 [1] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rd_data_w_clock_ultra_high_speed_program = {
    .instructions = rd_data_w_clock_ultra_high_speed_program_instructions,
    .length = 6,
    .origin = -1,
};

static inline pio_sm_config rd_data_w_clock_ultra_high_speed_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rd_data_w_clock_ultra_high_speed_wrap_target, offset + rd_data_w_clock_ultra_high_speed_wrap);
    sm_config_set_sideset(&c, 3, false, false);
    return c;
}

static inline pio_sm_config pio_rd_data_w_clock_ultra_high_speed_program_config(uint offset, uint d0_pin, uint clk_pin, float clk_div) {
  pio_sm_config c = rd_data_w_clock_ultra_high_speed_program_get_default_config(offset);
  sm_config_set_sideset_pins(&c, clk_pin - 2);
  sm_config_set_in_pins(&c, d0_pin);
  sm_config_set_jmp_pin(&c, d0_pin);
  sm_config_set_in_shift(&c, false, true, 32);
  sm_config_set_out_shift(&c, false, true, 32);
  sm_config_set_clkdiv(&c, clk_div);
  return c;
}

#endif

// --------------- //
// sdio_tx_w_clock //
// --------------- //

#define sdio_tx_w_clock_wrap_target 8
#define sdio_tx_w_clock_wrap 8

static const uint16_t sdio_tx_w_clock_program_instructions[] = {
    0x6e04, //  0: out    pins, 4         side 3 [2] 
    0x1d40, //  1: jmp    x--, 0          side 7 [1] 
    0xea80, //  2: set    pindirs, 0      side 2 [2] 
    0x1ac2, //  3: jmp    pin, 2          side 6 [2] 
    0x5b01, //  4: in     pins, 1         side 6 [3] 
    0x0b84, //  5: jmp    y--, 4          side 2 [3] 
    0x1bc8, //  6: jmp    pin, 8          side 6 [3] 
    0x0b06, //  7: jmp    6               side 2 [3] 
            //     .wrap_target
    0x8840, //  8: push   iffull noblock  side 2     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program sdio_tx_w_clock_program = {
    .instructions = sdio_tx_w_clock_program_instructions,
    .length = 9,
    .origin = -1,
};

static inline pio_sm_config sdio_tx_w_clock_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sdio_tx_w_clock_wrap_target, offset + sdio_tx_w_clock_wrap);
    sm_config_set_sideset(&c, 3, false, false);
    return c;
}

static inline pio_sm_config pio_sdio_tx_w_clock_program_config(uint offset, uint data_pin, uint clk_pin, float clk_div) {
    pio_sm_config c = sdio_tx_w_clock_program_get_default_config(offset);
    sm_config_set_sideset_pins(&c, clk_pin - 2);
    sm_config_set_out_pins(&c, data_pin, 4);
    sm_config_set_in_pins(&c, data_pin);
    sm_config_set_set_pins(&c, data_pin, 4);
    sm_config_set_in_shift(&c, false, false, 8);
    sm_config_set_out_shift(&c, false, true, 32);
    sm_config_set_jmp_pin(&c, data_pin);
    sm_config_set_clkdiv(&c, clk_div);
    return c;
}


#endif
