// Copyright (C) 2025 Tech by Androda, LLC
// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// shift //
// ----- //

#define shift_wrap_target 0
#define shift_wrap 0

static const uint16_t shift_program_instructions[] = {
            //     .wrap_target
    0x6001, //  0: out    pins, 1                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program shift_program = {
    .instructions = shift_program_instructions,
    .length = 1,
    .origin = -1,
};

static inline pio_sm_config shift_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + shift_wrap_target, offset + shift_wrap);
    return c;
}

static inline void shift_program_init(PIO pio, uint sm, uint offset, uint pin) {
    pio_sm_config c = shift_program_get_default_config(offset);
    // Map the state machine's OUT pin group to one pin, namely the `pin` parameter to this function.
    sm_config_set_out_pins(&c, pin, 1);
    // Set shift size 16
    sm_config_set_out_shift(&c, false, true, 16);
    // Join the TX fifo so we have more wiggle room
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);

    // Set this pin's GPIO function (connect PIO to the pad)
    pio_gpio_init(pio, pin);
    // Set the pin direction to output at the PIO
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    // Load our configuration, and jump to the start of the program
    pio_sm_init(pio, sm, offset, &c);
    
    // Set the state machine running
    pio_sm_set_enabled(pio, sm, true);
}

#endif
