#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = `wx-config --cflags` -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = `wx-config --libs`

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/TestApp

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  -s $(LDFLAGS)
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/TestApp

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/GTerm/states.o $(OBJDIR_DEBUG)/src/terminalwx.o $(OBJDIR_DEBUG)/src/terminalinputevent.o $(OBJDIR_DEBUG)/src/taTelnet/wxterm.o $(OBJDIR_DEBUG)/src/GTerm/vt52_states.o $(OBJDIR_DEBUG)/src/GTerm/utils.o $(OBJDIR_DEBUG)/TestApp.o $(OBJDIR_DEBUG)/src/GTerm/keytrans.o $(OBJDIR_DEBUG)/src/GTerm/gterm.o $(OBJDIR_DEBUG)/src/GTerm/actions.o $(OBJDIR_DEBUG)/TestMain.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/GTerm/states.o $(OBJDIR_RELEASE)/src/terminalwx.o $(OBJDIR_RELEASE)/src/terminalinputevent.o $(OBJDIR_RELEASE)/src/taTelnet/wxterm.o $(OBJDIR_RELEASE)/src/GTerm/vt52_states.o $(OBJDIR_RELEASE)/src/GTerm/utils.o $(OBJDIR_RELEASE)/TestApp.o $(OBJDIR_RELEASE)/src/GTerm/keytrans.o $(OBJDIR_RELEASE)/src/GTerm/gterm.o $(OBJDIR_RELEASE)/src/GTerm/actions.o $(OBJDIR_RELEASE)/TestMain.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src/GTerm || mkdir -p $(OBJDIR_DEBUG)/src/GTerm
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src
	test -d $(OBJDIR_DEBUG)/src/taTelnet || mkdir -p $(OBJDIR_DEBUG)/src/taTelnet
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/GTerm/states.o: src/GTerm/states.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/GTerm/states.cpp -o $(OBJDIR_DEBUG)/src/GTerm/states.o

$(OBJDIR_DEBUG)/src/terminalwx.o: src/terminalwx.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/terminalwx.cpp -o $(OBJDIR_DEBUG)/src/terminalwx.o

$(OBJDIR_DEBUG)/src/terminalinputevent.o: src/terminalinputevent.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/terminalinputevent.cpp -o $(OBJDIR_DEBUG)/src/terminalinputevent.o

$(OBJDIR_DEBUG)/src/taTelnet/wxterm.o: src/taTelnet/wxterm.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/taTelnet/wxterm.cpp -o $(OBJDIR_DEBUG)/src/taTelnet/wxterm.o

$(OBJDIR_DEBUG)/src/GTerm/vt52_states.o: src/GTerm/vt52_states.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/GTerm/vt52_states.cpp -o $(OBJDIR_DEBUG)/src/GTerm/vt52_states.o

$(OBJDIR_DEBUG)/src/GTerm/utils.o: src/GTerm/utils.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/GTerm/utils.cpp -o $(OBJDIR_DEBUG)/src/GTerm/utils.o

$(OBJDIR_DEBUG)/TestApp.o: TestApp.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c TestApp.cpp -o $(OBJDIR_DEBUG)/TestApp.o

$(OBJDIR_DEBUG)/src/GTerm/keytrans.o: src/GTerm/keytrans.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/GTerm/keytrans.cpp -o $(OBJDIR_DEBUG)/src/GTerm/keytrans.o

$(OBJDIR_DEBUG)/src/GTerm/gterm.o: src/GTerm/gterm.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/GTerm/gterm.cpp -o $(OBJDIR_DEBUG)/src/GTerm/gterm.o

$(OBJDIR_DEBUG)/src/GTerm/actions.o: src/GTerm/actions.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/GTerm/actions.cpp -o $(OBJDIR_DEBUG)/src/GTerm/actions.o

$(OBJDIR_DEBUG)/TestMain.o: TestMain.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c TestMain.cpp -o $(OBJDIR_DEBUG)/TestMain.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src/GTerm
	rm -rf $(OBJDIR_DEBUG)/src
	rm -rf $(OBJDIR_DEBUG)/src/taTelnet
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src/GTerm || mkdir -p $(OBJDIR_RELEASE)/src/GTerm
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src
	test -d $(OBJDIR_RELEASE)/src/taTelnet || mkdir -p $(OBJDIR_RELEASE)/src/taTelnet
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/GTerm/states.o: src/GTerm/states.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/GTerm/states.cpp -o $(OBJDIR_RELEASE)/src/GTerm/states.o

$(OBJDIR_RELEASE)/src/terminalwx.o: src/terminalwx.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/terminalwx.cpp -o $(OBJDIR_RELEASE)/src/terminalwx.o

$(OBJDIR_RELEASE)/src/terminalinputevent.o: src/terminalinputevent.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/terminalinputevent.cpp -o $(OBJDIR_RELEASE)/src/terminalinputevent.o

$(OBJDIR_RELEASE)/src/taTelnet/wxterm.o: src/taTelnet/wxterm.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/taTelnet/wxterm.cpp -o $(OBJDIR_RELEASE)/src/taTelnet/wxterm.o

$(OBJDIR_RELEASE)/src/GTerm/vt52_states.o: src/GTerm/vt52_states.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/GTerm/vt52_states.cpp -o $(OBJDIR_RELEASE)/src/GTerm/vt52_states.o

$(OBJDIR_RELEASE)/src/GTerm/utils.o: src/GTerm/utils.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/GTerm/utils.cpp -o $(OBJDIR_RELEASE)/src/GTerm/utils.o

$(OBJDIR_RELEASE)/TestApp.o: TestApp.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c TestApp.cpp -o $(OBJDIR_RELEASE)/TestApp.o

$(OBJDIR_RELEASE)/src/GTerm/keytrans.o: src/GTerm/keytrans.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/GTerm/keytrans.cpp -o $(OBJDIR_RELEASE)/src/GTerm/keytrans.o

$(OBJDIR_RELEASE)/src/GTerm/gterm.o: src/GTerm/gterm.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/GTerm/gterm.cpp -o $(OBJDIR_RELEASE)/src/GTerm/gterm.o

$(OBJDIR_RELEASE)/src/GTerm/actions.o: src/GTerm/actions.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/GTerm/actions.cpp -o $(OBJDIR_RELEASE)/src/GTerm/actions.o

$(OBJDIR_RELEASE)/TestMain.o: TestMain.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c TestMain.cpp -o $(OBJDIR_RELEASE)/TestMain.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src/GTerm
	rm -rf $(OBJDIR_RELEASE)/src
	rm -rf $(OBJDIR_RELEASE)/src/taTelnet
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

